version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  python_service:
    build: 
      context: . 
    container_name: python_service
    depends_on:
      - timescaledb
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    command: >
      bash -c "python -m migrations.config_migration &&
               python -m benchmark_tool.cli data/query_params.csv --workers 10 &&
               tail -f /dev/null"
